driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: bento/centos-5.11
  - name: bento/centos-6.7
  - name: bento/centos-7.2

suites:
  - name: default
    run_list:
      - recipe[yum-webtatic::default]
