AllCops:
  Excludes:
    - vendor/**

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

LineLength:
  Max: 200

MethodLength:
  Enabled: false

RedundantBegin:
  Enabled: false

UselessAssignment:
  Enabled: false
