language: ruby
install: bundle install --without integration --deployment --jobs=3 --retry=3
sudo: false
cache:
  directories:
    - vendor/bundle
rvm:
  - 2.0
  - 2.1
  - 2.2
script:
  - bundle exec rake travis
